AWSTemplateFormatVersion: 2010-09-09
Description: Amazon SageMaker notebook instance.

Resources:
  smnotebooks3accesspolicyD8836A4E:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Statement:
        - Action: s3:*
          Effect: Allow
          Resource: arn:aws:s3:::*
        Version: '2012-10-17'
      Description: ''
      Path: "/"
  titanicpipelinesmnotebookexecutionrole9C7C4C01:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: sagemaker.amazonaws.com
        Version: '2012-10-17'
      ManagedPolicyArns:
      - Fn::Join:
        - ''
        - - 'arn:'
          - Ref: AWS::Partition
          - ":iam::aws:policy/AmazonSageMakerFullAccess"
      - Ref: smnotebooks3accesspolicyD8836A4E
  titanicpipelinenotebook:
    Type: AWS::SageMaker::NotebookInstance
    Properties:
      InstanceType: ml.t3.medium
      RoleArn:
        Fn::GetAtt:
        - titanicpipelinesmnotebookexecutionrole9C7C4C01
        - Arn


Resources:
  smnotebooks3accesspolicyD8836A4E:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Statement:
        - Action: s3:*
          Effect: Allow
          Resource: arn:aws:s3:::*
        Version: '2012-10-17'
      Description: ''
      Path: "/"
  titanicpipelinesmnotebookexecutionrole9C7C4C01:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: sagemaker.amazonaws.com
        Version: '2012-10-17'
      ManagedPolicyArns:
      - Fn::Join:
        - ''
        - - 'arn:'
          - Ref: AWS::Partition
          - ":iam::aws:policy/AmazonSageMakerFullAccess"
      - Ref: smnotebooks3accesspolicyD8836A4E
      - Fn::Join:
        - ''
        - - 'arn:'
          - Ref: AWS::Partition
          - ":iam::aws:policy/AWSStepFunctionsFullAccess"
  titanicpipelinenotebook:
    Type: AWS::SageMaker::NotebookInstance
    Properties:
      InstanceType: ml.t3.medium
      RoleArn:
        Fn::GetAtt:
        - titanicpipelinesmnotebookexecutionrole9C7C4C01
        - Arn
      DefaultCodeRepository: https://github.com/tkazusa/kaggle-mlpipeline-titanic.git
  stepfunctionsworkflowexectionrole4C366CBA:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
              Fn::Join:
              - ''
              - - states.
                - Ref: AWS::Region
                - ".amazonaws.com"
        Version: '2012-10-17'
      ManagedPolicyArns:
      - Fn::Join:
        - ''
        - - 'arn:'
          - Ref: AWS::Partition
          - ":iam::aws:policy/CloudWatchEventsFullAccess"
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - sagemaker:CreateTransformJob
            - sagemaker:DescribeTransformJob
            - sagemaker:StopTransformJob
            - sagemaker:CreateProcessingJob
            - sagemaker:DescribeProcessingJob
            - sagemaker:StopProcessingJob
            - sagemaker:CreateTrainingJob
            - sagemaker:DescribeTrainingJob
            - sagemaker:StopTrainingJob
            - sagemaker:CreateHyperParameterTuningJob
            - sagemaker:DescribeHyperParameterTuningJob
            - sagemaker:StopHyperParameterTuningJob
            - sagemaker:CreateModel
            - sagemaker:CreateEndpointConfig
            - sagemaker:CreateEndpoint
            - sagemaker:DeleteEndpointConfig
            - sagemaker:DeleteEndpoint
            - sagemaker:UpdateEndpoint
            - sagemaker:ListTags
            - lambda:InvokeFunction
            - sqs:SendMessage
            - sns:Publish
            - ecs:RunTask
            - ecs:StopTask
            - ecs:DescribeTasks
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - batch:SubmitJob
            - batch:DescribeJobs
            - batch:TerminateJob
            - glue:StartJobRun
            - glue:GetJobRun
            - glue:GetJobRuns
            - glue:BatchStopJobRun
            Effect: Allow
            Resource: "*"
          - Action: iam:PassRole
            Condition:
              StringEquals:
                iam:PassedToService: sagemaker.amazonaws.com
            Effect: Allow
            Resource: "*"
          - Action:
            - events:PutTargets
            - events:PutRule
            - events:DescribeRule
            Effect: Allow
            Resource:
            - arn:aws:events:*:*:rule/StepFunctionsGetEventsForSageMakerTrainingJobsRule
            - arn:aws:events:*:*:rule/StepFunctionsGetEventsForSageMakerTransformJobsRule
            - arn:aws:events:*:*:rule/StepFunctionsGetEventsForSageMakerTuningJobsRule
            - arn:aws:events:*:*:rule/StepFunctionsGetEventsForECSTaskRule
            - arn:aws:events:*:*:rule/StepFunctionsGetEventsForBatchJobsRule
          Version: '2012-10-17'
        PolicyName: sfn-inline-policy